### ISSUE TITLE
Document docker-compose.yml setup

### ISSUE THREAD

**Issue by broganboyer** [torservers/onionize-docker#8]
Hello,

Nice project.

Just wanted to share a `docker-compose.yml` that could be used as an alternative to all the docker commands. It could be included somehow in the README like many docker image projects do.

```
version: "3"

services:
    web:
        image: nginx:alpine
        environment:
            - ONIONSERVICE_NAME=web
        networks:
            - faraday
    onion-service:
        image: torservers/onionize
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - faraday
            - internet

networks:
    faraday:
        driver_opts:
            com.docker.network.bridge.enable_ip_masquerade: "false"
    internet:
```
